# Generated by Django 5.0 on 2024-01-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bus_alter_room_unique_together_remove_room_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='seatNumber',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
